services:
  hapi-fhir-au:
    build: .
    container_name: hapi-fhir-au
    # restart: on-failure
    env_file: env/.app.env
    ports:
      - "3700:8080"
    depends_on:
      - hapi-fhir-postgres

  hapi-fhir-postgres:
    image: postgres:alpine
    container_name: hapi-fhir-postgres
    # restart: always
    env_file: env/.db.env
    ports:
      - "5432:5432"
