name: FHIR AU Test Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      COMPOSE_PROJECT_NAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{github.ref_name }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Copy Docker certs to the remote machine
      run: |
        mkdir -p /home/runner/work/.docker
        echo "${{ secrets.DOCKER_CA_CERT }}" > /home/runner/work/.docker/ca.pem
        echo "${{ secrets.DOCKER_CLIENT_CERT }}" > /home/runner/work/.docker/cert.pem
        echo "${{ secrets.DOCKER_CLIENT_KEY }}" > /home/runner/work/.docker/key.pem
    - name: Docker Compose Up
      run: |
        export DOCKER_HOST=tcp://13.239.21.231:2376
        export DOCKER_TLS_VERIFY=1
        export DOCKER_CERT_PATH=/home/runner/work/.docker
        echo ${{ env.COMPOSE_PROJECT_NAME }}
        echo ${{ COMPOSE_PROJECT_NAME }}
        export COMPOSE_PROJECT_NAME=${{ env.COMPOSE_PROJECT_NAME }}
        docker-compose up -d --build